<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNJXjeA1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNJXjeA1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNJXjeA1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNJXjeA1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNJXjeA1\App_KernelDevDebugContainer([
    'container.build_hash' => 'NJXjeA1',
    'container.build_id' => 'a465a24c',
    'container.build_time' => 1656518887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNJXjeA1');
